### ISSUE TITLE
Axios does not save cookies when running in node environment

### ISSUE THREAD

**Issue by Yserz** [wireapp/wire-web-api-client#10]
While Axios does implement cookie handling in browsers it seems this is not the case when running in an node environment.

Axios itself points to it's ecosystem:
https://github.com/mzabriskie/axios/issues/48

If we are following this advice we should pick up `axios-cookiejar-support` as a dependency:
https://github.com/3846masa/axios-cookiejar-support

A custom implementation may look like this:
... receiving a cookie
```js
let cookie : string;
return this.client.sendJSONRequest(config)
  .then((response: AxiosResponse) => {
    cookie = response.headers['set-cookie'][0];
    return response;
  })
  .then((response: AxiosResponse) => {
    return response.data;
  });
```
... sending with cookie
```js
const config: AxiosRequestConfig = {
  headers: {
    cookie: cookie,
    withCredentials: true
  },
    method: 'post',
    url: `${AuthAPI.URL.ACCESS}`
  };
```

**Comment by herrmannplatz** [comment]
should be?

```
const config: AxiosRequestConfig = {
  withCredentials: true
  headers: {
    cookie: cookie,
  },
  method: 'post',
  url: `${AuthAPI.URL.ACCESS}`
};
```

**Comment by vikas-parashar** [comment]
+1

**Comment by bennyn** [comment]
This issue will be solved with https://github.com/wireapp/wire-web-api-client/pull/112

Alternative implementation (using "axios-cookiejar-support"): https://github.com/wireapp/wire-web-api-client/tree/cookie-jar

**Comment by bennyn** [comment]
Done in https://github.com/wireapp/wire-web-api-client/releases/tag/v0.1.2
