### ISSUE TITLE
Fix flaky test: WebSocketClient "connect" automatically reconnects with a WebSocket.

### ISSUE THREAD

**Issue by bennyn** [wireapp/wire-web-api-client#129]
The Test `"connect" automatically reconnects with a WebSocket` is flaky. 

See here: 
https://travis-ci.org/wireapp/wire-web-api-client/builds/260111080

**Comment by bennyn** [comment]
Looks like the flakiness only shows up when there are two builds in parallel on Travis CI.

**Comment by ffflorian** [comment]
By now it's so flaky that it fails on almost every PR commit.

**Comment by bennyn** [comment]
Got fixed as part of https://github.com/wireapp/wire-web-api-client/pull/216
